# Generated by Django 4.0.6 on 2022-08-09 21:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.filepath),
        ),
    ]
