# Generated by Django 4.0.6 on 2022-08-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stores_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='stores',
            name='supplier_id',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.supplier'),
            preserve_default=False,
        ),
    ]
